# Generated by Django 2.2 on 2019-08-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_mapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='gone',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
